### ISSUE TITLE
Reason for adding the new Docker playground approach

### ISSUE THREAD

**Issue by marharyta-morozova** [fulldecent/moodle-local_plugin_template#23]
Hi @fulldecent 

I tested several approaches to run Moodle + the High Five plugin in Docker, including the current approach in the README, Multipass Canonical, and Podman. The easiest solution, in my opinion, is Docker Compose + Bitnami Moodle Docker solution + (optionally) Portainer. It is OS-independent and completely open-source.

Why it’s better than the current approach:

1. [OrbStack](https://orbstack.dev/) is for Mac only. For Linux and Windows, we would need to search for another solution, making the instructions longer. It is not open-source and provides only a 30-day trial period.
2. With [Moodle Docker](https://github.com/moodlehq/moodle-docker.git), we are running 5 containers (for now, to simplify setup, only the database and Moodle are required).
![!](https://github.com/user-attachments/assets/c69d034d-87e7-478c-9c1a-e63eacc738e6)
3. I faced several issues due to the setup process.
4. we don't need tree time to git clone

For now, the proposed approach works well with Linux. I plan to test it on Mac and Windows — it should work properly. However, it worked until the installation of the High Five plugin, as there is currently an issue with the installation process itself. I am working on fixing it. That said, I have tested the new Docker approach with the installation of several plugins. Also, it might be a better solution to create a separate README for the Docker playground to keep the main one shorter.

**Comment by fulldecent** [comment]
Thanks for sharing your progress here. We'll need it to work on Mac before merging since so many Moodle users that are teachers (and decide which plugins to use) run Mac.

---

As for where to put these instructions... the most important part of our README (and every README) is to invite new people (teachers, who figuratively can't even spell "PHP") to install and try the software. So this must be in the main file and not demoted to elsewhere.

---

As for Windows and Linux, these are not a priority. The Mac instructions must work and they must work well. (Oksana can install without any help in under 5 minutes.) If alternate approaches make installing on Mac harder then that is bad.

P.S. Many teachers do NOT have admin privileges on their work computers. OrbStack does NOT require admin privileges. Docker Desktop DOES require admin privileges to run. Therefore Docker Desktop is an unacceptable recommendation as it removes many potential teachers from trying our software.

**Comment by fulldecent** [comment]
Docker instructions updated in 61c0b428cbea59a1edbfcf92ab42ec4bf86e015b.

Closing this issue, happy to review further if when there is a specific suggestion that is better than current version.
